project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://justcallitaction.cfd # you must change this appropriately for RSS feeds to work properly
  title: "Just Call It Action"
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/optics-notes/index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kermanqi
      - icon: bluesky
        href: https://bsky.app/profile/justcallitaction.cfd
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
    css: styles.css



